//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 

namespace Roster.Presentation.Controls.NAVproxy
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "CreateTimeSheetLines_Binding", Namespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines")]
    public partial class CreateTimeSheetLines_Service : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;

        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;

        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;

        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;

        private System.Threading.SendOrPostCallback CreateOperationCompleted;

        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;

        private System.Threading.SendOrPostCallback UpdateOperationCompleted;

        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;

        private System.Threading.SendOrPostCallback DeleteOperationCompleted;

        /// <remarks/>
        public CreateTimeSheetLines_Service()
        {
            this.Url = "http://localhost:7047/TEST/WS/Koomarri/Page/CreateTimeSheetLines";
        }

        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;

        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;

        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;

        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;

        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;

        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;

        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;

        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;

        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/createtimesheetlines:ReadByRecId", RequestNamespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines", ResponseElementName = "ReadByRecId_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("CreateTimeSheetLines")]
        public CreateTimeSheetLines ReadByRecId(string recId)
        {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                    recId});
            return ((CreateTimeSheetLines)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginReadByRecId(string recId, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ReadByRecId", new object[] {
                    recId}, callback, asyncState);
        }

        /// <remarks/>
        public CreateTimeSheetLines EndReadByRecId(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((CreateTimeSheetLines)(results[0]));
        }

        /// <remarks/>
        public void ReadByRecIdAsync(string recId)
        {
            this.ReadByRecIdAsync(recId, null);
        }

        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState)
        {
            if ((this.ReadByRecIdOperationCompleted == null))
            {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                    recId}, this.ReadByRecIdOperationCompleted, userState);
        }

        private void OnReadByRecIdOperationCompleted(object arg)
        {
            if ((this.ReadByRecIdCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/createtimesheetlines:ReadMultiple", RequestNamespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines", ResponseElementName = "ReadMultiple_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public CreateTimeSheetLines[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] CreateTimeSheetLines_Filter[] filter, string bookmarkKey, int setSize)
        {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                    filter,
                    bookmarkKey,
                    setSize});
            return ((CreateTimeSheetLines[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginReadMultiple(CreateTimeSheetLines_Filter[] filter, string bookmarkKey, int setSize, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ReadMultiple", new object[] {
                    filter,
                    bookmarkKey,
                    setSize}, callback, asyncState);
        }

        /// <remarks/>
        public CreateTimeSheetLines[] EndReadMultiple(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((CreateTimeSheetLines[])(results[0]));
        }

        /// <remarks/>
        public void ReadMultipleAsync(CreateTimeSheetLines_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }

        /// <remarks/>
        public void ReadMultipleAsync(CreateTimeSheetLines_Filter[] filter, string bookmarkKey, int setSize, object userState)
        {
            if ((this.ReadMultipleOperationCompleted == null))
            {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                    filter,
                    bookmarkKey,
                    setSize}, this.ReadMultipleOperationCompleted, userState);
        }

        private void OnReadMultipleOperationCompleted(object arg)
        {
            if ((this.ReadMultipleCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/createtimesheetlines:IsUpdated", RequestNamespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines", ResponseElementName = "IsUpdated_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key)
        {
            object[] results = this.Invoke("IsUpdated", new object[] {
                    Key});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginIsUpdated(string Key, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("IsUpdated", new object[] {
                    Key}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndIsUpdated(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void IsUpdatedAsync(string Key)
        {
            this.IsUpdatedAsync(Key, null);
        }

        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState)
        {
            if ((this.IsUpdatedOperationCompleted == null))
            {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                    Key}, this.IsUpdatedOperationCompleted, userState);
        }

        private void OnIsUpdatedOperationCompleted(object arg)
        {
            if ((this.IsUpdatedCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/createtimesheetlines:GetRecIdFromKey", RequestNamespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines", ResponseElementName = "GetRecIdFromKey_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key)
        {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                    Key});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetRecIdFromKey(string Key, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetRecIdFromKey", new object[] {
                    Key}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetRecIdFromKey(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key)
        {
            this.GetRecIdFromKeyAsync(Key, null);
        }

        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState)
        {
            if ((this.GetRecIdFromKeyOperationCompleted == null))
            {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                    Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }

        private void OnGetRecIdFromKeyOperationCompleted(object arg)
        {
            if ((this.GetRecIdFromKeyCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/createtimesheetlines:Create", RequestNamespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines", ResponseElementName = "Create_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref CreateTimeSheetLines CreateTimeSheetLines)
        {
            object[] results = this.Invoke("Create", new object[] {
                    CreateTimeSheetLines});
            CreateTimeSheetLines = ((CreateTimeSheetLines)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCreate(CreateTimeSheetLines CreateTimeSheetLines, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Create", new object[] {
                    CreateTimeSheetLines}, callback, asyncState);
        }

        /// <remarks/>
        public void EndCreate(System.IAsyncResult asyncResult, out CreateTimeSheetLines CreateTimeSheetLines)
        {
            object[] results = this.EndInvoke(asyncResult);
            CreateTimeSheetLines = ((CreateTimeSheetLines)(results[0]));
        }

        /// <remarks/>
        public void CreateAsync(CreateTimeSheetLines CreateTimeSheetLines)
        {
            this.CreateAsync(CreateTimeSheetLines, null);
        }

        /// <remarks/>
        public void CreateAsync(CreateTimeSheetLines CreateTimeSheetLines, object userState)
        {
            if ((this.CreateOperationCompleted == null))
            {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                    CreateTimeSheetLines}, this.CreateOperationCompleted, userState);
        }

        private void OnCreateOperationCompleted(object arg)
        {
            if ((this.CreateCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/createtimesheetlines:CreateMultiple", RequestNamespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines", ResponseElementName = "CreateMultiple_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)] ref CreateTimeSheetLines[] CreateTimeSheetLines_List)
        {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                    CreateTimeSheetLines_List});
            CreateTimeSheetLines_List = ((CreateTimeSheetLines[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCreateMultiple(CreateTimeSheetLines[] CreateTimeSheetLines_List, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CreateMultiple", new object[] {
                    CreateTimeSheetLines_List}, callback, asyncState);
        }

        /// <remarks/>
        public void EndCreateMultiple(System.IAsyncResult asyncResult, out CreateTimeSheetLines[] CreateTimeSheetLines_List)
        {
            object[] results = this.EndInvoke(asyncResult);
            CreateTimeSheetLines_List = ((CreateTimeSheetLines[])(results[0]));
        }

        /// <remarks/>
        public void CreateMultipleAsync(CreateTimeSheetLines[] CreateTimeSheetLines_List)
        {
            this.CreateMultipleAsync(CreateTimeSheetLines_List, null);
        }

        /// <remarks/>
        public void CreateMultipleAsync(CreateTimeSheetLines[] CreateTimeSheetLines_List, object userState)
        {
            if ((this.CreateMultipleOperationCompleted == null))
            {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                    CreateTimeSheetLines_List}, this.CreateMultipleOperationCompleted, userState);
        }

        private void OnCreateMultipleOperationCompleted(object arg)
        {
            if ((this.CreateMultipleCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/createtimesheetlines:Update", RequestNamespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines", ResponseElementName = "Update_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref CreateTimeSheetLines CreateTimeSheetLines)
        {
            object[] results = this.Invoke("Update", new object[] {
                    CreateTimeSheetLines});
            CreateTimeSheetLines = ((CreateTimeSheetLines)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginUpdate(CreateTimeSheetLines CreateTimeSheetLines, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Update", new object[] {
                    CreateTimeSheetLines}, callback, asyncState);
        }

        /// <remarks/>
        public void EndUpdate(System.IAsyncResult asyncResult, out CreateTimeSheetLines CreateTimeSheetLines)
        {
            object[] results = this.EndInvoke(asyncResult);
            CreateTimeSheetLines = ((CreateTimeSheetLines)(results[0]));
        }

        /// <remarks/>
        public void UpdateAsync(CreateTimeSheetLines CreateTimeSheetLines)
        {
            this.UpdateAsync(CreateTimeSheetLines, null);
        }

        /// <remarks/>
        public void UpdateAsync(CreateTimeSheetLines CreateTimeSheetLines, object userState)
        {
            if ((this.UpdateOperationCompleted == null))
            {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                    CreateTimeSheetLines}, this.UpdateOperationCompleted, userState);
        }

        private void OnUpdateOperationCompleted(object arg)
        {
            if ((this.UpdateCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/createtimesheetlines:UpdateMultiple", RequestNamespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines", ResponseElementName = "UpdateMultiple_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)] ref CreateTimeSheetLines[] CreateTimeSheetLines_List)
        {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                    CreateTimeSheetLines_List});
            CreateTimeSheetLines_List = ((CreateTimeSheetLines[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginUpdateMultiple(CreateTimeSheetLines[] CreateTimeSheetLines_List, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UpdateMultiple", new object[] {
                    CreateTimeSheetLines_List}, callback, asyncState);
        }

        /// <remarks/>
        public void EndUpdateMultiple(System.IAsyncResult asyncResult, out CreateTimeSheetLines[] CreateTimeSheetLines_List)
        {
            object[] results = this.EndInvoke(asyncResult);
            CreateTimeSheetLines_List = ((CreateTimeSheetLines[])(results[0]));
        }

        /// <remarks/>
        public void UpdateMultipleAsync(CreateTimeSheetLines[] CreateTimeSheetLines_List)
        {
            this.UpdateMultipleAsync(CreateTimeSheetLines_List, null);
        }

        /// <remarks/>
        public void UpdateMultipleAsync(CreateTimeSheetLines[] CreateTimeSheetLines_List, object userState)
        {
            if ((this.UpdateMultipleOperationCompleted == null))
            {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                    CreateTimeSheetLines_List}, this.UpdateMultipleOperationCompleted, userState);
        }

        private void OnUpdateMultipleOperationCompleted(object arg)
        {
            if ((this.UpdateMultipleCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/createtimesheetlines:Delete", RequestNamespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines", ResponseElementName = "Delete_Result", ResponseNamespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key)
        {
            object[] results = this.Invoke("Delete", new object[] {
                    Key});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginDelete(string Key, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Delete", new object[] {
                    Key}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndDelete(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void DeleteAsync(string Key)
        {
            this.DeleteAsync(Key, null);
        }

        /// <remarks/>
        public void DeleteAsync(string Key, object userState)
        {
            if ((this.DeleteOperationCompleted == null))
            {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                    Key}, this.DeleteOperationCompleted, userState);
        }

        private void OnDeleteOperationCompleted(object arg)
        {
            if ((this.DeleteCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines")]
    public partial class CreateTimeSheetLines
    {

        private string keyField;

        private string external_Time_Sheet_NoField;

        private System.DateTime time_Sheet_Starting_DateField;

        private bool time_Sheet_Starting_DateFieldSpecified;

        private string resource_NoField;

        private Type typeField;

        private bool typeFieldSpecified;

        private string job_NoField;

        private string job_Task_NoField;

        private string cause_of_Absence_CodeField;

        private string descriptionField;

        private string work_Type_CodeField;

        private bool chargeableField;

        private bool chargeableFieldSpecified;

        private bool non_Roster_DayField;

        private bool non_Roster_DayFieldSpecified;

        private decimal qty1Field;

        private bool qty1FieldSpecified;

        private decimal qty2Field;

        private bool qty2FieldSpecified;

        private decimal qty3Field;

        private bool qty3FieldSpecified;

        private decimal qty4Field;

        private bool qty4FieldSpecified;

        private decimal qty5Field;

        private bool qty5FieldSpecified;

        private decimal qty6Field;

        private bool qty6FieldSpecified;

        private decimal qty7Field;

        private bool qty7FieldSpecified;

        private System.DateTime start_TimeField;

        private bool start_TimeFieldSpecified;

        private System.DateTime end_TimeField;

        private bool end_TimeFieldSpecified;

        /// <remarks/>
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        public string External_Time_Sheet_No
        {
            get
            {
                return this.external_Time_Sheet_NoField;
            }
            set
            {
                this.external_Time_Sheet_NoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime Time_Sheet_Starting_Date
        {
            get
            {
                return this.time_Sheet_Starting_DateField;
            }
            set
            {
                this.time_Sheet_Starting_DateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Time_Sheet_Starting_DateSpecified
        {
            get
            {
                return this.time_Sheet_Starting_DateFieldSpecified;
            }
            set
            {
                this.time_Sheet_Starting_DateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Resource_No
        {
            get
            {
                return this.resource_NoField;
            }
            set
            {
                this.resource_NoField = value;
            }
        }

        /// <remarks/>
        public Type Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Job_No
        {
            get
            {
                return this.job_NoField;
            }
            set
            {
                this.job_NoField = value;
            }
        }

        /// <remarks/>
        public string Job_Task_No
        {
            get
            {
                return this.job_Task_NoField;
            }
            set
            {
                this.job_Task_NoField = value;
            }
        }

        /// <remarks/>
        public string Cause_of_Absence_Code
        {
            get
            {
                return this.cause_of_Absence_CodeField;
            }
            set
            {
                this.cause_of_Absence_CodeField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string Work_Type_Code
        {
            get
            {
                return this.work_Type_CodeField;
            }
            set
            {
                this.work_Type_CodeField = value;
            }
        }

        /// <remarks/>
        public bool Chargeable
        {
            get
            {
                return this.chargeableField;
            }
            set
            {
                this.chargeableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChargeableSpecified
        {
            get
            {
                return this.chargeableFieldSpecified;
            }
            set
            {
                this.chargeableFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool Non_Roster_Day
        {
            get
            {
                return this.non_Roster_DayField;
            }
            set
            {
                this.non_Roster_DayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Non_Roster_DaySpecified
        {
            get
            {
                return this.non_Roster_DayFieldSpecified;
            }
            set
            {
                this.non_Roster_DayFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal Qty1
        {
            get
            {
                return this.qty1Field;
            }
            set
            {
                this.qty1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty1Specified
        {
            get
            {
                return this.qty1FieldSpecified;
            }
            set
            {
                this.qty1FieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal Qty2
        {
            get
            {
                return this.qty2Field;
            }
            set
            {
                this.qty2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty2Specified
        {
            get
            {
                return this.qty2FieldSpecified;
            }
            set
            {
                this.qty2FieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal Qty3
        {
            get
            {
                return this.qty3Field;
            }
            set
            {
                this.qty3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty3Specified
        {
            get
            {
                return this.qty3FieldSpecified;
            }
            set
            {
                this.qty3FieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal Qty4
        {
            get
            {
                return this.qty4Field;
            }
            set
            {
                this.qty4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty4Specified
        {
            get
            {
                return this.qty4FieldSpecified;
            }
            set
            {
                this.qty4FieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal Qty5
        {
            get
            {
                return this.qty5Field;
            }
            set
            {
                this.qty5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty5Specified
        {
            get
            {
                return this.qty5FieldSpecified;
            }
            set
            {
                this.qty5FieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal Qty6
        {
            get
            {
                return this.qty6Field;
            }
            set
            {
                this.qty6Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty6Specified
        {
            get
            {
                return this.qty6FieldSpecified;
            }
            set
            {
                this.qty6FieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal Qty7
        {
            get
            {
                return this.qty7Field;
            }
            set
            {
                this.qty7Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty7Specified
        {
            get
            {
                return this.qty7FieldSpecified;
            }
            set
            {
                this.qty7FieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime Start_Time
        {
            get
            {
                return this.start_TimeField;
            }
            set
            {
                this.start_TimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Start_TimeSpecified
        {
            get
            {
                return this.start_TimeFieldSpecified;
            }
            set
            {
                this.start_TimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime End_Time
        {
            get
            {
                return this.end_TimeField;
            }
            set
            {
                this.end_TimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool End_TimeSpecified
        {
            get
            {
                return this.end_TimeFieldSpecified;
            }
            set
            {
                this.end_TimeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines")]
    public enum Type
    {

        /// <remarks/>
        _blank_,

        /// <remarks/>
        Resource,

        /// <remarks/>
        Job,

        /// <remarks/>
        Service,

        /// <remarks/>
        Absence,

        /// <remarks/>
        Assembly_Order,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines")]
    public partial class CreateTimeSheetLines_Filter
    {

        private CreateTimeSheetLines_Fields fieldField;

        private string criteriaField;

        /// <remarks/>
        public CreateTimeSheetLines_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }

        /// <remarks/>
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:microsoft-dynamics-schemas/page/createtimesheetlines")]
    public enum CreateTimeSheetLines_Fields
    {

        /// <remarks/>
        External_Time_Sheet_No,

        /// <remarks/>
        Time_Sheet_Starting_Date,

        /// <remarks/>
        Resource_No,

        /// <remarks/>
        Type,

        /// <remarks/>
        Job_No,

        /// <remarks/>
        Job_Task_No,

        /// <remarks/>
        Cause_of_Absence_Code,

        /// <remarks/>
        Description,

        /// <remarks/>
        Work_Type_Code,

        /// <remarks/>
        Chargeable,

        /// <remarks/>
        Non_Roster_Day,

        /// <remarks/>
        Qty1,

        /// <remarks/>
        Qty2,

        /// <remarks/>
        Qty3,

        /// <remarks/>
        Qty4,

        /// <remarks/>
        Qty5,

        /// <remarks/>
        Qty6,

        /// <remarks/>
        Qty7,

        /// <remarks/>
        Start_Time,

        /// <remarks/>
        End_Time,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public CreateTimeSheetLines Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((CreateTimeSheetLines)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public CreateTimeSheetLines[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((CreateTimeSheetLines[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public CreateTimeSheetLines CreateTimeSheetLines
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((CreateTimeSheetLines)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public CreateTimeSheetLines[] CreateTimeSheetLines_List
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((CreateTimeSheetLines[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public CreateTimeSheetLines CreateTimeSheetLines
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((CreateTimeSheetLines)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public CreateTimeSheetLines[] CreateTimeSheetLines_List
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((CreateTimeSheetLines[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

}