//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.Model.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessControlItem
    {
        public System.Guid Id { get; set; }
        public System.Guid ListMetadataId { get; set; }
        public System.Guid ItemId { get; set; }
        public int TrusteeId { get; set; }
        public int AccessRight { get; set; }
    
        public virtual RosterEvent RosterEvent { get; set; }
        public virtual ListMetadata ListMetadata { get; set; }
    }
}
