//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.Model.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public Holiday()
        {
            this.HolidayEvents = new HashSet<HolidayEvent>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public int TypeId { get; set; }
    
        public virtual HolidayType HolidayType { get; set; }
        public virtual ICollection<HolidayEvent> HolidayEvents { get; set; }
    }
}
