//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.Model.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayEvent
    {
        public HolidayEvent()
        {
            this.HolidayObserveds = new HashSet<HolidayObserved>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime HolidayDate { get; set; }
        public System.Guid HolidayId { get; set; }
        public string Weekday { get; set; }
    
        public virtual ICollection<HolidayObserved> HolidayObserveds { get; set; }
        public virtual Holiday Holiday { get; set; }
    }
}
