//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.Model.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayObserved
    {
        public System.Guid Id { get; set; }
        public System.Guid HolidayEventId { get; set; }
        public int StateId { get; set; }
    
        public virtual State State { get; set; }
        public virtual HolidayEvent HolidayEvent { get; set; }
    }
}
