//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlSync.Model.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListMapping
    {
        public ListMapping()
        {
            this.ListMappingFields = new HashSet<ListMappingField>();
        }
    
        public System.Guid Id { get; set; }
        public string ListName { get; set; }
        public string TableName { get; set; }
        public string Key { get; set; }
    
        public virtual ICollection<ListMappingField> ListMappingFields { get; set; }
    }
}
