//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.Model.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListMetadata
    {
        public ListMetadata()
        {
            this.ListMetadataActions = new HashSet<ListMetadataAction>();
            this.ListMetadataContentTypes = new HashSet<ListMetadataContentType>();
            this.ListMetadataFields = new HashSet<ListMetadataField>();
            this.ViewMetadatas = new HashSet<ViewMetadata>();
            this.AccessControlItems = new HashSet<AccessControlItem>();
            this.AccessControlLists = new HashSet<AccessControlList>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string DataSource { get; set; }
    
        public virtual ICollection<ListMetadataAction> ListMetadataActions { get; set; }
        public virtual ICollection<ListMetadataContentType> ListMetadataContentTypes { get; set; }
        public virtual ICollection<ListMetadataField> ListMetadataFields { get; set; }
        public virtual ICollection<ViewMetadata> ViewMetadatas { get; set; }
        public virtual ICollection<AccessControlItem> AccessControlItems { get; set; }
        public virtual ICollection<AccessControlList> AccessControlLists { get; set; }
    }
}
