//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.Model.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListMetadataField
    {
        public ListMetadataField()
        {
            this.ViewMetadataFields = new HashSet<ViewMetadataField>();
            this.ViewMetadataPopupSettings = new HashSet<ViewMetadataPopupSetting>();
            this.ViewMetadataWhereCriteries = new HashSet<ViewMetadataWhereCritery>();
            this.ListMetadataFieldContentTypes = new HashSet<ListMetadataFieldContentType>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ListMetadataId { get; set; }
        public string InternalName { get; set; }
        public string FieldName { get; set; }
        public string Description { get; set; }
        public string FieldType { get; set; }
        public string DefaultValue { get; set; }
        public string DataSource { get; set; }
        public string DataSourceKey { get; set; }
        public string DataSourceField { get; set; }
        public int DataSourceType { get; set; }
        public bool IsStatic { get; set; }
        public bool Required { get; set; }
        public bool ReadOnly { get; set; }
        public bool Hidden { get; set; }
        public string ControlProperties { get; set; }
        public Nullable<int> ItemPosition { get; set; }
    
        public virtual ICollection<ViewMetadataField> ViewMetadataFields { get; set; }
        public virtual ICollection<ViewMetadataPopupSetting> ViewMetadataPopupSettings { get; set; }
        public virtual ICollection<ViewMetadataWhereCritery> ViewMetadataWhereCriteries { get; set; }
        public virtual ListMetadata ListMetadata { get; set; }
        public virtual ICollection<ListMetadataFieldContentType> ListMetadataFieldContentTypes { get; set; }
    }
}
