//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.Model.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListMetadataAction
    {
        public System.Guid Id { get; set; }
        public System.Guid ListMetadataId { get; set; }
        public string LabelText { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string ImageUrl { get; set; }
        public string Command { get; set; }
        public string AccessGroup { get; set; }
        public int ContentTypeId { get; set; }
    
        public virtual ListMetadata ListMetadata { get; set; }
        public virtual ListMetadataContentType ListMetadataContentType { get; set; }
    }
}
