//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.Model.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListMetadataFieldContentType
    {
        public System.Guid Id { get; set; }
        public int ContentTypeId { get; set; }
        public System.Guid ListMetadataFieldId { get; set; }
        public Nullable<int> ItemPosition { get; set; }
    
        public virtual ListMetadataContentType ListMetadataContentType { get; set; }
        public virtual ListMetadataField ListMetadataField { get; set; }
    }
}
