//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.Model.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RosterEvent
    {
        public RosterEvent()
        {
            this.AccessControlItems = new HashSet<AccessControlItem>();
        }
    
        public System.Guid Id { get; set; }
        public int EventTypeId { get; set; }
    
        public virtual ICollection<AccessControlItem> AccessControlItems { get; set; }
    }
}
