//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlSync.Model.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;

    public partial class SqlSyncEntities : DbContext
    {
        public SqlSyncEntities()
            : base("name=SqlSyncEntities")
        {
        }

        public SqlSyncEntities(string connectionString)
             : base(connectionString)
        {
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<SystemOption> SystemOptions { get; set; }
        public virtual DbSet<ListMapping> ListMappings { get; set; }
        public virtual DbSet<ListMappingField> ListMappingFields { get; set; }
    }
}
