//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.Model.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMetadata
    {
        public ViewMetadata()
        {
            this.ViewMetadataFields = new HashSet<ViewMetadataField>();
            this.ViewMetadataPopupSettings = new HashSet<ViewMetadataPopupSetting>();
            this.ViewMetadataWhereCriteries = new HashSet<ViewMetadataWhereCritery>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ListMetadataId { get; set; }
        public string Name { get; set; }
        public string DisplayType { get; set; }
        public string ViewData { get; set; }
        public string CalendarScope { get; set; }
        public int ItemLimit { get; set; }
        public bool IsDefault { get; set; }
        public string DynamicColourCodingSettings { get; set; }
        public string StaticColourCodingSettings { get; set; }
        public string ExcludeFields { get; set; }
    
        public virtual ICollection<ViewMetadataField> ViewMetadataFields { get; set; }
        public virtual ICollection<ViewMetadataPopupSetting> ViewMetadataPopupSettings { get; set; }
        public virtual ICollection<ViewMetadataWhereCritery> ViewMetadataWhereCriteries { get; set; }
        public virtual ListMetadata ListMetadata { get; set; }
    }
}
