//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.Model.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRosterEventTrackData
    {
        public System.Guid Id { get; set; }
        public System.Guid RosterEventId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string XmlContent { get; set; }
        public Nullable<long> Version { get; set; }
    }
}
