//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roster.BL.Providers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roster.BL.Providers.SqlTemplate", typeof(SqlTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER VIEW dbo.[{0}] AS {1}.
        /// </summary>
        internal static string AlterStatements_Query {
            get {
                return ResourceManager.GetString("AlterStatements_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW dbo.[{0}] AS {1}.
        /// </summary>
        internal static string CreateStatements_Query {
            get {
                return ResourceManager.GetString("CreateStatements_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM dbo.sysobjects WHERE id = OBJECT_ID(N&apos;{0}&apos;)
        ///  .
        /// </summary>
        internal static string ExistsStatements_Query {
            get {
                return ResourceManager.GetString("ExistsStatements_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE dbo.[{0}] ALTER COLUMN [{1}] {2} NULL.
        /// </summary>
        internal static string Field_Alter {
            get {
                return ResourceManager.GetString("Field_Alter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE dbo.[{0}] ADD [{1}] {2} NULL.
        /// </summary>
        internal static string Field_Create {
            get {
                return ResourceManager.GetString("Field_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE dbo.[{0}] DROP COLUMN [{1}].
        /// </summary>
        internal static string Field_Delete {
            get {
                return ResourceManager.GetString("Field_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(1) FROM sys.columns WHERE [object_id] =OBJECT_ID(N&apos;{0}&apos;) and [name] =  N&apos;{1}&apos;.
        /// </summary>
        internal static string Field_Exists {
            get {
                return ResourceManager.GetString("Field_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	CREATE INDEX [IX_{0}_{1}] ON [{0}]([{1}]).
        /// </summary>
        internal static string Index_Create {
            get {
                return ResourceManager.GetString("Index_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS(SELECT * FROM sys.indexes WHERE object_id = object_id(&apos;{0}&apos;) AND NAME =&apos;IX_{0}_{1}&apos;)
        ///        DROP INDEX IX_{0}_{1} ON [{0}].
        /// </summary>
        internal static string Index_Delete {
            get {
                return ResourceManager.GetString("Index_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COLUMN_NAME from information_schema.COLUMNS WHERE TABLE_NAME = &apos;{0}&apos; ORDER BY ORDINAL_POSITION.
        /// </summary>
        internal static string ListFields_Query {
            get {
                return ResourceManager.GetString("ListFields_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COLUMN_NAME from information_schema.COLUMNS WHERE TABLE_NAME = &apos;{0}&apos; AND DATA_TYPE = &apos;int&apos; ORDER BY ORDINAL_POSITION.
        /// </summary>
        internal static string ListKeyFields_Query {
            get {
                return ResourceManager.GetString("ListKeyFields_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  AND TABLE_NAME NOT IN ({0}).
        /// </summary>
        internal static string ListTable_WhereClause {
            get {
                return ResourceManager.GetString("ListTable_WhereClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TABLE_NAME FROM information_schema.tables WHERE TABLE_TYPE =&apos;BASE TABLE&apos; AND TABLE_NAME NOT LIKE &apos;%Property&apos; {0}.
        /// </summary>
        internal static string ListTables_SelectClause {
            get {
                return ResourceManager.GetString("ListTables_SelectClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_helptext &apos;{0}&apos;
        ///  .
        /// </summary>
        internal static string ReadStatements_Query {
            get {
                return ResourceManager.GetString("ReadStatements_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM dbo.[{0}] WHERE {1}.
        /// </summary>
        internal static string Row_Delete {
            get {
                return ResourceManager.GetString("Row_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT dbo.[{0}]({1}) VALUES({2}).
        /// </summary>
        internal static string Row_Insert {
            get {
                return ResourceManager.GetString("Row_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE dbo.[{0}] SET {1} WHERE {2}.
        /// </summary>
        internal static string Row_Update {
            get {
                return ResourceManager.GetString("Row_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PRIMARY XML INDEX [PK_{0}_{1}] ON [{0}]([{1}]).
        /// </summary>
        internal static string XmlPrimaryIndex_Create {
            get {
                return ResourceManager.GetString("XmlPrimaryIndex_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS(SELECT * FROM sys.indexes WHERE object_id = object_id(&apos;{0}&apos;) AND NAME =&apos;PK_{0}_{1}&apos;)
        ///        DROP INDEX PK_{0}_{1} ON [{0}].
        /// </summary>
        internal static string XmlPrimaryIndex_Drop {
            get {
                return ResourceManager.GetString("XmlPrimaryIndex_Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE XML INDEX [IX_{0}_{1}] ON [{0}]([{1}]) USING XML INDEX PK_{0}_{1} FOR PROPERTY.
        /// </summary>
        internal static string XmlPropertyIndex_Create {
            get {
                return ResourceManager.GetString("XmlPropertyIndex_Create", resourceCulture);
            }
        }
    }
}
